# Generated by Django 5.1.1 on 2025-08-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hourly_rate',
        ),
    ]
