# Generated by Django 5.1.1 on 2025-10-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_App', '0002_subservice_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='subservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Service_App.subservice'),
        ),
    ]
