# Generated by Django 5.1.1 on 2025-10-05 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service_App', '0003_booking_subservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='s_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='s_name',
            new_name='name',
        ),
    ]
