# Generated by Django 5.1.1 on 2025-10-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_App', '0004_rename_s_id_service_id_rename_s_name_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subservices/'),
        ),
    ]
